version: "3.8"

services:
  node_backend:
    container_name: node_express
    image: node_express_sequelize:0.0.3
    build:
      context: .
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
      - PGDATABASE=yedidya_db
      - PGUSER=root
      - PGPASSWORD=root
      - PGHOST=node_db
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=yedidya_db
    volumes:
      - nps_data:/var/postgresql/nps_data
volumes:
  nps_data: {}
